name: Telegram Hourly Post

on:
  schedule:
    # Runs at minute 0 of every hour
    - cron: '0 * * * *'
  # Allows you to manually trigger the script from GitHub to test it
  workflow_dispatch:

jobs:
  post-to-telegram:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests

      - name: Run Telegram Script
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHANNEL_ID: ${{ secrets.CHANNEL_ID }}
        run: python main.py
