name: Telegram Hourly Post

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  post-to-telegram:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v6

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests

      - name: Run Telegram Script
        env:
          Kreegyrbot: ${{ secrets.Kreegyrbot }}
          CHANNEL_ID: ${{ secrets.8767695621:AAFv11-DCnAGcJ2oTIWUlT20XBdTpJsBCQs }}
        run: python main.py
